-- Hunt: Flimsy Lost Soul - Blue Valley
-- Generated by /hunt save (flood-fill from Position(33613, 31415, 8))

local hunt = HuntInstance({
    name = "Flimsy Lost Soul - Blue Valley",
    caveSeed = Position(33613, 31415, 8),
    exit = Position(31904, 32348, 9),
    requiredLevel = 0,
    cooldownTime = 0,
    maxInstances = 20,
})
hunt:register()

-- Discovered teleport entries:
--   (31904,32346,9) -> (33573,31461,8)
--   (33886,31784,8) -> (33581,31466,9)
--   (32883,32518,7) -> (33613,31415,8)
--   (32884,32518,7) -> (33613,31415,8)
-- Discovered exit teleports:
--   (33572,31459,8) -> (31904,32348,9)
--   (33581,31465,9) -> (33887,31786,8)
-- Internal teleports: 10
